### ISSUE TITLE
Create component for minimised post

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#1]
Create a React component for the minimised post (the post title that is visible on the main screen, and if clicked opens up the actual post content).

- The component should take two props - the post author's name, and the post title.
- It should show just a card with the post title and the author's name.

**Comment by Zark84010** [comment]
[Aditya Ranjan](https://github.com/Zark84010) and [Devanshu Singla](https://github.com/devanshusingla/) are taking up this task.
