### ISSUE TITLE
Create login screen

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#12]
Create the login screen for the app.
Here are some guidelines:
- Create a folder named `login` in the screens folder, and work inside that folder. If you need to make any new components for use in the login screen, add them to the components folder.
- The screen should have two text fields: IITK username and password. There should also be a checkbox for "Remember me".
- Again, click logic isn't important. Just add two functions in the screen component - one that is called when checkbox is ticked or unticked (name `onRemember`), and one called when user clicks on login (name `onLogin`).
- You can add a state variable to keep track of the checkbox status.

The screen design (and any other ideas you have) is entirely up to you. Just don't make it too heavy :)

**Comment by kartikcode** [comment]
Please assign this task to me.🙂

**Comment by SD-320808** [comment]
Shivam Malhotra and Diya Singhal are taking up this task.

**Comment by NilayMajorwar** [comment]
Closed by #18.
