### ISSUE TITLE
Create comment section component

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#14]
This is a slightly tougher task.

You need to create a component for the comment section that will be shown below a maximised post. This is what the component is supposed to do:
- It should take a prop that contains all the comments of a post. Remember that we have layered comments (like Reddit), so you need to take care about the comment hierarchy.
- Then, it should display each comment correctly, with proper left-indentation to show the hierarchy.

The prop that the component will receive will have a recursive-like structure:
```
[
  {
    id: 57,
    text: "Comment text 1",
    author: "John Doe",
    replies: [
      {
        id: 74,
        text: "Nested comment text 1",
        author: "Dohn Joe",
        replies: [ ...nested replies... ]
      }, ... other replies ...
    ]
  },
  ... other comments ...
]
```

There is already a component (`Comment`) for displaying a single comment. Use that to display the individual comments. You'll probably have to make some changes to that component too (add some new props, etc).

Also, this component should have the following functions too:
- `onUpvote(commentId)`: Called when the user upvotes any comment. `commentId` is the id of the comment upvoted.
- `onDownvote(commentId)`: Similar to `onUpvote`.
- `onReply(commentId, text)`: Called when the uses replies on a comment. `commentId` is the id of comment replied to, and `text` is the reply text.

For now, don't care about where these functions are called. Just ensure that these three functions are passed as props to every `Comment` component so that the `Comment` component can use them later on. Add any prop (for example `id`) to `Comment` component that you think will be necessary.

**Comment by devanshusingla** [comment]
Devanshu and Aditya are taking up this issue.
