### ISSUE TITLE
Add reply box to comment

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#15]
Add a collapsible reply box in the `Comment` component. It should be collapsed by default, and clicking the reply button should toggle it. The reply box should have a textbox and a send button. 

Right now, the Reply icon button calls the `onReply` function defined in the component. Change it to toggle the expand state. Clicking the Send button should now call this `onReply` function.

See the Card component in Material UI. There's an example of a collapsible section in a card. Have a look at that, and try to implement this.

**Comment by NupurJ** [comment]
Keerthana, Panshul, and I will be taking up this task.
