### ISSUE TITLE
Create component for maximised post

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#2]
Create a React component for the maximised post - the one that opens when you click on a post in the stream view.

- The component should take the following props:
   - The post title
   - The post content
   - The author's name

Right now, this is enough. We'll add support for external posts (Facebook, Twitter, etc) later.

**Comment by ShivamMalhotra1994** [comment]
Diya Singhal and Shivam Malhotra are taking up this task.

**Comment by NilayMajorwar** [comment]
Closed with #10
