### ISSUE TITLE
Create screen for writing post

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#22]
Create a screen for writing a new post. The screen should have text boxes for post title, post content, a file picker for adding image, and obviously the submit button.

The component should take a prop `onSubmit` whose value will be a function. This prop function should be called with the user-entered post title, content and image as arguments when the user clicks on the submit button. You can add any other props that you require (stream name, for example).

**Comment by ShivamMalhotra1994** [comment]
Shivam Malhotra and Diya Singhal are taking up this task.
