### ISSUE TITLE
Create mainframe component

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#23]
Create the mainframe component of the whole app. This component will be responsible for handling navigation throughout the app, and some other things that are not relevant right now.

For now, the main part of this task is routing and state management. 
- You need to set up routes for all the screens of the app (at least those made till now). You can use libraries like `react-router` or `react-navigation` for doing this.
- Add state to this component to keep track of stuff, like what stream is open right now.

**Comment by devanshusingla** [comment]
devanshu and aditya are taking this issue.
