### ISSUE TITLE
Create screen for all streams

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#24]
Create a new screen for displaying all the streams and subscribing to any stream.

The component should take a prop called `onSubscribe` and `onOpen`, both of which are functions. The screen should show a list of streams, each not-yet-subscribed stream having a button for subscribing.

When the user subscribes to a stream, the prop `onSubscribe` should be called with stream ID as the argument, and the stream should be shown as subscribed.

Similarly, if the user clicks on an already subscribed stream, the prop `onOpen` should be called with stream ID as the argument. Don't worry about navigating to the stream page yet.

For now, you can add hardcoded data for all streams in a JSON file in the folder you make for the screen, and then import the JSON file in your component to use it. The data will be an array of stream objects like this: 
```
{
  id: 45,
  title: "Some Stream",
  description: "This is some stream",
  followers: 245
}
```

**Comment by NupurJ** [comment]
Keerthana, Panshul and Nupur will be taking up this task.
