### ISSUE TITLE
Create sidebar component

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#3]
Create a React component for the sidebar.

The component should take the following props:
- An array of names of subscribed streams (we'll implement unread indicator later).
- The user's name (to show profile)

Right now, don't worry about what happens on clicking. Just make clicking on any stream or button do a `console.log('Clicked!')` :)

**Comment by NupurJ** [comment]
Keerthana, Panshul and Nupur are taking up this task
