### ISSUE TITLE
Add Redux to the app

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#35]
Add a Redux store and corresponding selectors, actions and reducers to the app. 

The store should maintain the following information:
- The user's profile
- List of subscribed streams 
Each stream should be an object with properties for at least id and name - you can add any other properties that may be necessary (feel free to ask)
- ID of currently active stream (or null, if no stream is currently open)

Add selectors for information that may be used by components. For eg:
- List of subscribed streams (will be used by sidebar)
- Currently subscribed stream (will be used by several components)
- User's profile (will be used by topbar and profile page)

Add actions for tasks like:
- Adding new stream to subscribed streams (used when user subscribes to new stream)
- Removing a stream from subscribed streams (used when user unsubscribes from a stream)
- Set active stream ID (when user opens a stream or switches to another stream)

You can learn about Redux from the [official site](https://redux.js.org/introduction/getting-started). Feel free to ask any doubts!

**Comment by kartikcode** [comment]
I'll like to work on this issue.
