### ISSUE TITLE
Add request functions

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#36]
Most of the APIs in the backend are ready, so we can start creating functions for interacting with the backend. Create some functions for sending requests to the backend. You can use a library like Axios or fetch to send the requests. Refer to the backend repo to see the request and response format of the routes.

Keep all the requests in a single file, say `utils/requests.js`. 

- The backend's base URL should be stored in a separate variable in the file.
- Create a function for sending requests to a path - something like the following:
```
const sendRequest = async (method, path, body) => {
  // Use axios or fetch to send the request here
  // path: for eg: '/auth/login' - append this to the base url to get full url
  // return value: the response body. Throw an error if the response status code is not 200.
}
```
- Then, create a function for each request the app may need to send to the server. These functions will use the above function `sendRequest` for sending requests, and the arguments to these functions will be "nicer" than above. For example, the login function will probably look something similar to this:
```
const login = async (email, password) => {
  const res = await sendRequest('POST', '/auth/login', {email, password});
  return res;
}
```

For now, you can just add the most important requests - login, get subscribed streams, get all streams, get stream posts, create post, subscribe to stream, etc.

**Comment by Mshivam2409** [comment]
Shivam Malhotra and Diya Singhal will take up this issue
