### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#37]
Add dark mode support to the app.

Since we've used Material UI, this is pretty easy. Material UI has theme support, and also comes by default with a dark palette. Refer to the [MUI docs on dark mode](https://material-ui.com/customization/palette/#dark-mode).

**Comment by devanshusingla** [comment]
devanshu and aditya are taking this task

**Comment by devanshusingla** [comment]
close issue #38
