### ISSUE TITLE
Create topbar component

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#4]
Create a React component for the topbar.

The component should just take a prop for the title ("Home", "My Stream", etc) and make a topbar that has this title, a hamburger menu icon on the left, and a search button on the right.

Don't worry about clicking - just make it so that clicking on any button does a `console.log('Clicked')!`.

**Comment by devanshusingla** [comment]
devanshu singla & aditya ranjan are taking this task

**Comment by NilayMajorwar** [comment]
Closed with #6
