### ISSUE TITLE
Create a component for a single comment

### ISSUE THREAD

**Issue by NilayMajorwar** [pclubiitk/Campus-Discuss-Frontend#5]
Create a React component for a single comment.

The comment should take two props:
- The comment author's name
- The comment text

The component should show a single comment (like a Facebook comment, if you want). 

It should also have a button with a Reply icon somewhere, so that the user can add a reply comment. Don't worry about clicking - just make it so that clicking the button does a `console.log('Clicked!')` so that you know it works :)

**Comment by kartikcode** [comment]
I'll be taking up this task.

**Comment by NilayMajorwar** [comment]
Closed with e0068841b5fd90b55bae3b08f7caad981c10a7c9.
